// Auto-generated by Supabase CLI: npx supabase gen types typescript
// This file will be replaced once the Supabase project is connected.
// For now, it exports a placeholder type.

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
